<!doctype html>
<html class="no-js" lang="">

    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>Report Generator - SmartOrganizer</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">

        @include('health-logs.partials.pure-css')

        <style>
        	thead td{
        		font-weight: bold;
        	}

        	.table-heading{
        		font-weight: bold;
        		text-decoration: underline;
        		font-size: 15px;
        		margin-bottom: 20px;
        	}

        	.container{
        		margin-top: 20px;
        		margin-bottom: 20px;
        	}

        	.table-footer{
        		font-style: italic;
        		font-size: 12px;
        	}

        	table td, table th{
        		padding: 10px;
        	}

        	@page {
				header: page-header;
				footer: page-footer;
			}
        </style>

    </head>
    <body>
		<div class="container">

			<div class="row">
				<div class="col-md-12">
					<div class="text-center table-heading">
						Blood Pressure, Heart Rate and Weight Report
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-md-12 text-center">
					@if( $results->count() > 0)

						<table class="table table-bordered text-center">
							<thead>
								<tr>
									<td>Date</td>
									<td>Time</td>
									<td>BP Measurement</td>
									<td>Heart Rate</td>
									<td>Weight</td>
								</tr>
							</thead>

							<tbody>
								@foreach($results as $result)
								
								<tr>
									<td>{{ date_format( new DateTime($result->log_date), "d/m/Y") }}</td>
									<td>{{ date_format( new DateTime($result->log_time), "h:i:s A") }}</td>
									<td>{{ $result->bp == 1 ? $result->sys ." / ". $result->dia : '-' }}</td>
									<td>{{ $result->hr == 1 ? $result->h_rate : '-' }}</td>
									<td>{{ $result->wt == 1 ? $result->weight : '-' }}</td>
								</tr>

								@endforeach
							</tbody>

						</table>

					@else

						<table class="table table-bordered text-center">
							<tr>
								<th>No result was found!</th>
							</tr>
						</table>

					@endif

				</div>
			</div>
			<!--/row-->
			

		</div>
		<!--/container-->

		<htmlpagefooter name="page-footer">
			<div class="row">
				<div class="col-md-12">
					<div class="text-center table-footer">
						<span>Report Generated by <strong>SmartOrganizer</strong>. Date &amp; Time: {{ date('d/m/Y h:i:s A')}} </span>
					</div>
				</div>
			</div>
		</htmlpagefooter>

    </body>
</html>