<!doctype html>
<html class="no-js" lang="">

    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>Report Generator - SmartOrganizer</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

        <style>
        	
        </style>

    </head>
    <body>
		<div class="container">

			<div class="row">
				<div class="col-md-12">
					<div class="text-left">
						Blood Pressure, Heart Rate and Weight Report:
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-md-12">
					@if( $results->count() > 0)

						<table class="table table-bordered text-center">
							<tr>
								<th>Date</th>
								<th>Time</th>
								<th>BP Measurement</th>
								<th>Heart Rate</th>
								<th>Weight</th>
							</tr>

							@foreach($results as $result)
							
							<tr>
								<td>{{ date_format( new DateTime($result->log_date), "d/m/Y") }}</td>
								<td>{{ date_format( new DateTime($result->log_time), "h:i:s A") }}</td>
								<td>{{ $result->bp == 1 ? $result->sys ." / ". $result->dia : '-' }}</td>
								<td>{{ $result->hr == 1 ? $result->h_rate : '-' }}</td>
								<td>{{ $result->wt == 1 ? $result->weight : '-' }}</td>
							</tr>

							@endforeach

						</table>

					@else

						<table class="table table-bordered text-center">
							<tr>
								<th>No result was found!</th>
							</tr>
						</table>

					@endif

				</div>
			</div>
			<!--/row-->

			<div class="row">
				<div class="col-md-12">
					<div class="text-center">
						<span>Report Generated by SmartOrganizer. Time: {{ date('d-m-Y h:i:s A')}} </span>
					</div>
				</div>
			</div>

		</div>
		<!--/container-->

    </body>
</html>